# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: Install Dependencies
      run: yarn install
      working-directory: ./contracts
    - name: Run coverage tests
      run: npm run test:coverage
      working-directory: ./contracts
    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: solidity-coverage-report
        path: contracts/coverage/*
